var MyParser = require('parser'); //myparser.js is the file generated by jacob
var parser = new MyParser();

var MyLexer = require('lexer'); //mylexer.js being the file generated by jacob
var lexer = new MyLexer();

lexer.setInput('2+3');

// function getNextToken(lexer, line, col) {
//     token = null;
//     try {
//         token = lexer.nextToken();
//     } catch (SyntaxError) {
//         console.log("Syntax Error: Invalid token at Line: " + line + ", Column: " + col + ";\n");
//     }
// }

// while (true) {
// 	getNextToken(lexer, line, col);
// 	if (lexer.isEOF(token)) break;

// 	if (token == null) return;

// 	line = token.pos.line + 1;
// 	col = token.pos.col + 1;

// 	if (!(token.name in tokens)) {
// 		console.log("Syntax Error: Invalid token at Line: " + line + ", Column: " + col + "; \t \"" + token.name + "\"\n");
// 		return;
// 	}
// 	tokens[token.name].push(token.value);
// }

console.log(parser.parse(lexer));