
var MyLexer = require('mylexer'); //mylexer.js being the file generated by jacob
var lexer = new MyLexer();
lexer.setInput("break\n1234432");
 
var firstToken = lexer.nextToken();
console.log(firstToken);
while(!lexer.isEOF(firstToken)){
    firstToken=lexer.nextToken();
    console.log(firstToken);
}
console.log("EOF reached");