
var MyLexer = require('mylexer'); //mylexer.js being the file generated by jacob
var lexer = new MyLexer();
lexer.setInput('1234567890');
 
var firstToken = lexer.nextToken();
console.log(firstToken);
if(lexer.isEOF(firstToken)){
    console.log("EOF reached");
}